---
- hosts: local
  tasks:
    - command: echo "$PATH"
      register: default_path

    - name: brew deps
      apt: pkg={{ item }} 
      with_items:
        - build-essential
        - curl
        - git
        - python-setuptools
        - ruby

- hosts: local
- environment:
     PATH: "/home/ubuntu/.linuxbrew/bin:{{default_path.stdout}}"
     MANPATH: "/home/ubuntu/.linuxbrew/man"
     INFOPATH: "/home/ubuntu/.linuxbrew/info"
  hosts: local
  tasks:
    - name: install brew
      git: repo=https://github.com/Linuxbrew/brew.git dest=/home/ubuntu/.linuxbrew version=HEAD accept_hostkey=yes update=yes force=yes
      register: linuxbrew

    - name: brew bwa
      homebrew: name=homebrew/science/bwa state=present

    - name: brew samtools
      homebrew: name=homebrew/science/samtools state=present

    - homebrew: name={{item}}
      with_items:
        - homebrew/science/samtools
        - homebrew/science/canu
        - homebrew/science/busco
        - homebrew/science/miniasm
        - homebrew/science/minimap
        - homebrew/science/quast
        - homebrew/science/eilon
        - homebrew/science/bwa
        - homebrew/science/last
        - homebrew/science/kraken
        - homebrew/science/mummer
        - homebrew/science/nucmer
        - homebrew/science/mafft
        - homebrew/science/metaphlan
        - homebrew/science/sspace-longread
        - homebrew/science/bcftools
        - homebrew/science/picard-tools
        - homebrew/science/spades
        - homebrew/science/vcflib

