---
- hosts: local
  tasks:
   - name: build-essential
     apt: pkg=build-essential state=installed update_cache=true

   - name: zlib
     apt: pkg=zlib1g-dev state=installed update_cache=true

   - name: nanopolish 
     git: repo=https://github.com/jts/nanopolish.git dest=/home/ubuntu/src/nanopolish-master version=HEAD accept_hostkey=yes
     register: nanopolishgit

   - name: build nanopolish
     when: nanopolishgit|success
     make:
        chdir: /home/ubuntu/src/nanopolish-master
        params:
            NUM_THREADS: 8

   - git: repo=https://github.com/jts/nanopolish.git dest=/home/ubuntu/src/nanopolish-r7 version=v0.5.0 accept_hostkey=yes
     register: nanopolish-r7

   - when: nanopolish-r7|success
     make:
        chdir: /home/ubuntu/src/nanopolish-r7
        params:
            NUM_THREADS: 8
